# Generated by Django 4.2.8 on 2023-12-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title', models.CharField(max_length=70)),
                ('resume_developer_role', models.CharField(max_length=120)),
                ('resume_short_intro', models.TextField(max_length=200)),
                ('skill_summary', models.TextField()),
                ('resume_image', models.ImageField(default='avatar7.png', upload_to='images')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_description', models.CharField(max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=70)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('technologies_used', models.CharField(max_length=255)),
                ('project_summary', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.resume')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(max_length=255)),
                ('referrer_institution', models.CharField(max_length=255)),
                ('referrer_job_title', models.CharField(max_length=255)),
                ('referrer_phn', models.CharField(max_length=15)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_educational_qualification', models.CharField(max_length=70)),
                ('name_of_the_institution', models.CharField(max_length=120)),
                ('name_of_the_department', models.CharField(max_length=70)),
                ('passing_year', models.CharField(max_length=4)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile')),
            ],
        ),
    ]
