# Generated by Django 4.2.8 on 2023-12-14 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('developer_role', models.CharField(max_length=70)),
                ('short_intro', models.TextField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('address', models.CharField(max_length=70)),
                ('profile_image', models.ImageField(default='avatar7.png', upload_to='images/')),
                ('fathers_name', models.CharField(blank=True, max_length=70, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=70, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='male', max_length=15)),
                ('religion', models.CharField(blank=True, max_length=15, null=True)),
                ('nationality', models.CharField(blank=True, max_length=15, null=True)),
                ('martial_status', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
